name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 pandas matplotlib openpyxl reportlab pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile --windowed muhasebe_gui.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: muhasebe_gui-exe
          path: dist/muhasebe_gui.exe

